version: '3'
services:
  app:
    image: animacom_api
    container_name: animacom_api
    build:
      context: ../
      dockerfile: ./containers/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
