version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0
common_stepup_commaand: &common_stepup_commaand
  command: |
    echo 'export PATH=$PATH:${CIRCLE_WORKING_DIRECTORY}/script' >> $BASH_ENV
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          S3_ENDPOINT: http://localhost:4566
          S3_IMAGE_TEST_BUCKET: anima
          S3_ASSET_HOST: http://localhost:4566/anima/
          REDIS_URL: redis://127.0.0.1:6379
      - image: circleci/mysql:8.0.16
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
      - image: localstack/localstack:latest
        environment:
          SERVICES: s3
          DEFAULT_REGION: ap-northeast-1
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_ACCESS_KEY_ID: dummy
      - image: redis:latest
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_ACCESS_KEY_ID: dummy

    working_directory: ~/animacom-back
    steps:
      - checkout
      - aws-cli/setup
      - restore_cache:
          keys:
            - rails-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-bundle-v2-
      - run:
          name: bundle install
          command: bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: rails-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m
      - run:
          name: Confiure Database setting
          command: mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: TEST DB create
          command: bundle exec rake db:create
      - run:
          name: TEST S3 Bucket create
          command: aws --endpoint-url=http://localhost:4566 s3 mb s3://anima
      - run:
          name: Run rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"
            bundle exec rspec \
              --format progress \
              --out /tmp/test-results/rspec.xml \
              --format documentation \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  db_migrate:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          RAILS_ENV: test
    working_directory: ~/animacom-back
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: db migration
          command: |
            if is_changed "db"; then
              migrate
            else
              echo "dbに変更無し"
            fi
workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test
      - db_migrate:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - aws-ecr/build-and-push-image:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          dockerfile: containers/app/Dockerfile
          account-url: AWS_ACCOUNT_URL
          repo: '${AWS_RESOURCE_RAILS}'
          region: AWS_DEFAULT_REGION
          tag: latest
          extra-build-args: '--build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          family: 'animacom-task'
          cluster-name: 'animacom-cluster'
          service-name: 'animacom-service'
          container-image-name-updates: 'container=animacom_api,tag=latest'
